// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: smart_watch_ui

#include "../ui.h"

void ui_CalenderScreen_screen_init(void)
{
ui_CalenderScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CalenderScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalenderScreen, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalenderScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalendarComponent = lv_calendar_create(ui_CalenderScreen);
lv_calendar_set_today_date(ui_CalendarComponent,2024,5,12);
lv_calendar_set_showed_date(ui_CalendarComponent,2024,5);
lv_obj_t *ui_CalendarComponent_header = lv_calendar_header_arrow_create(ui_CalendarComponent);
lv_obj_set_width( ui_CalendarComponent, 190);
lv_obj_set_height( ui_CalendarComponent, 190);
lv_obj_set_align( ui_CalendarComponent, LV_ALIGN_CENTER );
lv_obj_set_style_border_color(ui_CalendarComponent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CalendarComponent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CalenderScreen, ui_event_CalenderScreen, LV_EVENT_ALL, NULL);

}
