// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: smart_watch_ui

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsTitle = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_SettingsTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsTitle, 0 );
lv_obj_set_y( ui_SettingsTitle, -90 );
lv_obj_set_align( ui_SettingsTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsTitle,"Settings");
lv_obj_set_style_text_font(ui_SettingsTitle, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackgroundPanel = lv_obj_create(ui_SettingsScreen);
lv_obj_set_width( ui_BackgroundPanel, 243);
lv_obj_set_height( ui_BackgroundPanel, 156);
lv_obj_set_x( ui_BackgroundPanel, -2 );
lv_obj_set_y( ui_BackgroundPanel, 12 );
lv_obj_set_align( ui_BackgroundPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BackgroundPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BrightnessSlider = lv_slider_create(ui_SettingsScreen);
lv_slider_set_value( ui_BrightnessSlider, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_BrightnessSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_BrightnessSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BrightnessSlider, 100);
lv_obj_set_height( ui_BrightnessSlider, 10);
lv_obj_set_x( ui_BrightnessSlider, 48 );
lv_obj_set_y( ui_BrightnessSlider, -35 );
lv_obj_set_align( ui_BrightnessSlider, LV_ALIGN_CENTER );

lv_obj_set_style_shadow_width(ui_BrightnessSlider, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BrightnessSlider, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BrightnessSlider, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BrightnessSlider, 2, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BrightnessLabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_BrightnessLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BrightnessLabel, -60 );
lv_obj_set_y( ui_BrightnessLabel, -35 );
lv_obj_set_align( ui_BrightnessLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BrightnessLabel,"Brightness");

ui_BLELabel = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_BLELabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BLELabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BLELabel, -56 );
lv_obj_set_y( ui_BLELabel, 0 );
lv_obj_set_align( ui_BLELabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BLELabel,"Bluetooth");

ui_VersionText = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_VersionText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VersionText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VersionText, -1 );
lv_obj_set_y( ui_VersionText, 72 );
lv_obj_set_align( ui_VersionText, LV_ALIGN_CENTER );
lv_label_set_text(ui_VersionText,"Version: 0.1.0");

ui_BluetoothSwitch = lv_switch_create(ui_SettingsScreen);
lv_obj_set_width( ui_BluetoothSwitch, 54);
lv_obj_set_height( ui_BluetoothSwitch, 25);
lv_obj_set_x( ui_BluetoothSwitch, 49 );
lv_obj_set_y( ui_BluetoothSwitch, -1 );
lv_obj_set_align( ui_BluetoothSwitch, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BluetoothSwitch, ui_event_BluetoothSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}
