// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: smart_watch_ui

#ifndef _SMART_WATCH_UI_UI_H
#define _SMART_WATCH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_event_HomeScreen( lv_event_t * e);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_SportSliderBiggerLeft;
extern lv_obj_t *ui_SportSliderBiggerRight;
extern lv_obj_t *ui_SportSlider;
extern lv_obj_t *ui_ClockText;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
void ui_event_SettingsScreen( lv_event_t * e);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_SettingsTitle;
extern lv_obj_t *ui_BackgroundPanel;
void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t *ui_BrightnessSlider;
void ui_event_WiFiSettings( lv_event_t * e);
extern lv_obj_t *ui_WiFiSettings;
extern lv_obj_t *ui_BrightnessLabel;
extern lv_obj_t *ui_WiFiLabel;
extern lv_obj_t *ui_VersionText;
// SCREEN: ui_CalenderScreen
void ui_CalenderScreen_screen_init(void);
void ui_event_CalenderScreen( lv_event_t * e);
extern lv_obj_t *ui_CalenderScreen;
extern lv_obj_t *ui_CalendarComponent;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
