// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: Test

#include "ui.h"
#include <lvgl.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/logging/log.h>
#include <zephyr/drivers/pwm.h>
#define LOG_LEVEL	CONFIG_LOG_DEFAULT_LEVEL
LOG_MODULE_REGISTER(LVGL_Callbacks, LOG_LEVEL_INF);


void wifi_value_changed(lv_event_t * e)
{
	// Your code here
}

void brightness_changed_callback(lv_obj_t * target, lv_event_t * e) {
	const struct pwm_dt_spec backlight = PWM_DT_SPEC_GET_BY_IDX(DT_NODELABEL(pwm_lcd0), 0);
    if (!pwm_is_ready_dt(&backlight)) {
        LOG_ERR("PWM device is not ready, exiting...");
    }

	// Normalize the slider value from 0-100 to 100-1000 range.
	int value = lv_slider_get_value(target);
	value = (value * 9) + 100;

    // Change the PWM pulse width according to slider value.
    int ret = pwm_set_dt(&backlight, 1000, value);
    if (ret < 0) {
        LOG_ERR("Failed to set PWM pulse, exiting...");
    }
}
