// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: smart_watch_ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void brightness_changed_callback(lv_event_t * e);
void ble_switch_callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
